### ISSUE TITLE
Auto-update, with update URL settings

### ISSUE THREAD

**Issue by denis-bogdanas** [ChangeOrientedProgrammingEnvironment/IntelliJ-test-recorder#8]

**Comment by nelsonni** [comment]
According to the IntelliJ IDEA documentation provided by JetBrains:
- **IntelliJ IDEA Plugins**
  The IntelliJ IDEA Plugin Manager also supports automatically updating installed plugins when new plugin versions are released. Source: [Install Plugins Using IntelliJ IDEA Plugin Manager](https://www.jetbrains.com/idea/plugins/)
- **To create a plugin archive**
  Right-click the plugin module in the Project view and select Prepare Plugin Module <module-name> For Deployment in the context menu. As a result, IntelliJ IDEA will create the necessary archive. Source: [Preparing Plugins for Publishing](https://www.jetbrains.com/idea/help/preparing-plugins-for-publishing.html).
- **Adding Plugins to Enterprise Repositories**
  To be available to IntelliJ IDEA users, all enterprise repository plugins must be listed in the file updatePlugins.xml along with their URLs and version numbers. This file must be available at the URL specified for the corresponding repository (see _Managing Enterprise Plugin Repositories_). The plugins themselves are identified by their individual URLs and thus may be located on different Web servers. Source: [Adding Plugins to Enterprise Repositories](https://www.jetbrains.com/idea/help/adding-plugins-to-enterprise-repositories.html).
- **Managing Enterprise Plugin Repositories**
  To be able to use plugin repositories other than the JetBrains Plugin Repository (e.g., your enterprise plugin repositories), you should specify the URLs of such repositories in IntelliJ IDEA. Source: [Managing Enterprise Plugin Repositories](https://www.jetbrains.com/idea/help/managing-enterprise-plugin-repositories.html).

**Comment by nelsonni** [comment]
- **Plugins & Categories of plugins**
  You can set up your own, enterprise plugin repositories, for example, to store plugins that you want to reserve for your company's internal use only. (A plugin repository corresponds to one or more Web servers.) Source: [Plugin repositories](https://www.jetbrains.com/idea/help/plugins.html#d1805450e147).

Since we require a running Enterprise Plugin Repository server in order to conduct further update mechanism testing and configuration, this issue must wait until we have such hardware/infrastructure.
